project_id = "tvneohngeracipjajzos"

[functions.verify-photo]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.translate-message]
verify_jwt = false

[functions.shift-scheduler]
verify_jwt = false

[functions.ai-women-approval]
verify_jwt = false

[functions.content-moderation]
verify_jwt = false

[functions.seed-legal-documents]
verify_jwt = false

[functions.data-cleanup]
verify_jwt = false

[functions.ai-women-manager]
verify_jwt = false

[functions.chat-manager]
verify_jwt = false

[functions.trigger-backup]
verify_jwt = false

[functions.seed-super-users]
verify_jwt = false

[functions.video-call-server]
verify_jwt = false

[functions.video-cleanup]
verify_jwt = false

[functions.group-cleanup]
verify_jwt = false

[functions.ai-election-manager]
verify_jwt = false

[functions.gender-detection]
verify_jwt = false
